apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    app: django
    tier: app
  ports:
    - protocol: TCP
      port: 8000
      name: app
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      containers:
        - image: djangoweather-django:latest
          # imagePullPolicy: Never
          name: app
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: port
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: ALLOWED_HOSTS
            - name: CORS_TRUSTED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: CORS_TRUSTED_ORIGINS
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DJANGO_SECRET_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_STORAGE_BUCKET_NAME
            - name: AWS_S3_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: AWS_S3_REGION_NAME

        - image: djangoweather-proxy:latest
          # imagePullPolicy: Never
          name: proxy
          ports:
            - containerPort: 8000
              name: proxy
